### ISSUE TITLE
[Windows 11] Сломанный парсинг HTML

### ISSUE THREAD

**Issue by dimas257** [YariKartoshe4ka/vk-messages-saver#11]
![image](https://github.com/YariKartoshe4ka/vk-messages-saver/assets/65215768/51c31da9-c5b1-4842-9b3e-4a47153dae28)

Был пропущен < /div >, из-за чего сообщения и "Стакнулись"
![image](https://github.com/YariKartoshe4ka/vk-messages-saver/assets/65215768/bff4c5e5-1702-48ea-9813-9fc24b046fa1)

Готов выдвинуть гипотезу, что это проблема с экранированием символов, так как в базе SQLite я нашёл данное сообщение
![image](https://github.com/YariKartoshe4ka/vk-messages-saver/assets/65215768/03186d66-0878-4b2e-8e55-16e6337d9791)
![image](https://github.com/YariKartoshe4ka/vk-messages-saver/assets/65215768/e3fbc379-db9d-435e-b5a3-143c460f01c0)

**Comment by YariKartoshe4ka** [comment]
Спасибо, будет исправлено в 1.0.3
