### ISSUE TITLE
HTML-диалог ломается о текстовые смайлики

### ISSUE THREAD

**Issue by Lucifer-is-my-pet** [YariKartoshe4ka/vk-messages-saver#17]
Скачала тестово небольшую переписку и прогнала через парсер обоих форматов. В html, кажется, из-за смайликов вида "<D" и "<:D" немного поломалась вёрстка

Оригинал чата (моя реплика - от 14:09 и соседняя)
![изображение](https://github.com/user-attachments/assets/a2f727e3-1892-41fe-a1f7-34109812414c)

Что на выходе из html-парсера
![изображение](https://github.com/user-attachments/assets/44fa13b9-306d-46ca-aaa4-fabdb700905e)

Один смайлик потерялся и чужие реплики всосались в мои 😅

**Comment by YariKartoshe4ka** [comment]
```python
pip install git+https://github.com/YariKartoshe4ka/vk-messages-saver
```

Когда-нибудь я сделаю релиз на pypi, хз
