### ISSUE TITLE
Вечный цикл

### ISSUE THREAD

**Issue by username391** [YariKartoshe4ka/vk-messages-saver#8]
Файл peers.py, функция download

```
processed = len(peers)

# Повторяем действия выше, пока все переписки не будут загружены
while processed < res['count']:
    res = api.messages.getConversations(offset=processed, count=200)
    peers += [item['conversation'] for item in res['items']]
```

Если количество диалогов больше 200 будет вечный цикл, количество уже собранных переписок получается только один раз до входа в цикл while. Возможно стоит добавить `processed = len(peers)` внутри цикла

**Comment by YariKartoshe4ka** [comment]
Спасибо, исправлю в 1.0.2
